#!/bin/sh
#
# This file was automatically generated by the Nios II IDE Flash Programmer.
#
# It will be overwritten when the flash programmer options change.
#

cd D:/MYSVN/de2_115/cd/DE2_115_demonstrations/DE2_115_mouse/DE2_115_NIOS_HOST_MOUSE_VGA/software/DE2_115_NIOS_HOST_MOUSE_VGA/Debug

# Creating .flash file for the project
"$SOPC_KIT_NIOS2/bin/elf2flash" --base=0x0a000000 --end=0xa7fffff --reset=0xa000000 --input="DE2_115_NIOS_HOST_MOUSE_VGA.elf" --output="cfi_flash.flash" --boot="C:/altera/10.0/ip/altera/nios2_ip/altera_nios2/boot_loader_cfi.srec"

# Programming flash with the project
"$SOPC_KIT_NIOS2/bin/nios2-flash-programmer" --base=0x0a000000 --sidp=0x09200070 --id=1457883068 --timestamp=1339674710  "cfi_flash.flash"

