<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?scdStore version="2"?>

<scannerInfo id="org.eclipse.cdt.make.core.discoveredScannerInfo">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="D:/NIOS_II/DE2_115_SD_CARD/Software"/>
<includePath path="d:/NIOS_II/DE2_115_SD_CARD/Software/DE2_115_SD_CARD_syslib/Debug/system_description"/>
<includePath path="c:/altera/91/ip/altera/sopc_builder_ip/altera_avalon_sysid/HAL/inc"/>
<includePath path="c:/altera/91/ip/altera/sopc_builder_ip/altera_avalon_sysid/inc"/>
<includePath path="c:/altera/91/ip/altera/sopc_builder_ip/altera_avalon_timer/HAL/inc"/>
<includePath path="c:/altera/91/ip/altera/sopc_builder_ip/altera_avalon_timer/inc"/>
<includePath path="c:/altera/91/ip/altera/sopc_builder_ip/altera_avalon_cfi_flash/HAL/inc"/>
<includePath path="c:/altera/91/ip/altera/sopc_builder_ip/altera_avalon_pio/inc"/>
<includePath path="c:/altera/91/ip/altera/sopc_builder_ip/altera_avalon_uart/HAL/inc"/>
<includePath path="c:/altera/91/ip/altera/sopc_builder_ip/altera_avalon_uart/inc"/>
<includePath path="c:/altera/91/ip/altera/sopc_builder_ip/altera_avalon_lcd_16207/HAL/inc"/>
<includePath path="c:/altera/91/ip/altera/sopc_builder_ip/altera_avalon_lcd_16207/inc"/>
<includePath path="c:/altera/91/ip/altera/sopc_builder_ip/altera_avalon_jtag_uart/HAL/inc"/>
<includePath path="c:/altera/91/ip/altera/sopc_builder_ip/altera_avalon_jtag_uart/inc"/>
<includePath path="c:/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc"/>
<includePath path="c:/altera/91/nios2eds/components/altera_hal/HAL/inc"/>
<includePath path="E:/SVN/DE2_115/trunk/ref_design/DE2_115_SD_CARD/Software/DE2_115_SD_CARD/terasic_fat"/>
<includePath path="E:/SVN/DE2_115/trunk/ref_design/DE2_115_SD_CARD/Software/DE2_115_SD_CARD/terasic_lib"/>
<includePath path="E:/SVN/DE2_115/trunk/ref_design/DE2_115_SD_CARD/Software/DE2_115_SD_CARD/terasic_sdcard"/>
<includePath path="C:/altera/10.0/quartus/bin/cygwin/lib/gcc/i686-pc-cygwin/3.4.4/include"/>
<includePath path="C:/altera/10.0/quartus/bin/cygwin/usr/include"/>
<includePath path="C:/altera/10.0/quartus/bin/cygwin/usr/include/w32api"/>
<includePath path="D:/NIOS_II/DE2_115_SD_CARD/Software/DE2_115_SD_CARD/terasic_fat"/>
<includePath path="D:/NIOS_II/DE2_115_SD_CARD/Software/DE2_115_SD_CARD/terasic_lib"/>
<includePath path="D:/NIOS_II/DE2_115_SD_CARD/Software/DE2_115_SD_CARD/terasic_sdcard"/>
<includePath path="c:/altera/91/quartus/bin/cygwin/lib/gcc/i686-pc-cygwin/3.4.4/include"/>
<includePath path="c:/altera/91/quartus/bin/cygwin/usr/include"/>
<includePath path="c:/altera/91/quartus/bin/cygwin/usr/include/w32api"/>
<includePath path="E:/SVN/DE2_115/trunk/ref_design/DE2_115_SD_CARD/Software"/>
<includePath path="e:/SVN/DE2_115/trunk/ref_design/DE2_115_SD_CARD/Software/DE2_115_SD_CARD_syslib/Debug/system_description"/>
<includePath path="c:/altera/10.0/ip/altera/sopc_builder_ip/altera_avalon_sysid/HAL/inc"/>
<includePath path="c:/altera/10.0/ip/altera/sopc_builder_ip/altera_avalon_sysid/inc"/>
<includePath path="c:/altera/10.0/ip/altera/sopc_builder_ip/altera_avalon_timer/HAL/inc"/>
<includePath path="c:/altera/10.0/ip/altera/sopc_builder_ip/altera_avalon_timer/inc"/>
<includePath path="c:/altera/10.0/ip/altera/sopc_builder_ip/altera_avalon_cfi_flash/HAL/inc"/>
<includePath path="c:/altera/10.0/ip/altera/sopc_builder_ip/altera_avalon_pio/inc"/>
<includePath path="c:/altera/10.0/ip/altera/sopc_builder_ip/altera_avalon_uart/HAL/inc"/>
<includePath path="c:/altera/10.0/ip/altera/sopc_builder_ip/altera_avalon_uart/inc"/>
<includePath path="c:/altera/10.0/ip/altera/sopc_builder_ip/altera_avalon_lcd_16207/HAL/inc"/>
<includePath path="c:/altera/10.0/ip/altera/sopc_builder_ip/altera_avalon_lcd_16207/inc"/>
<includePath path="c:/altera/10.0/ip/altera/sopc_builder_ip/altera_avalon_jtag_uart/HAL/inc"/>
<includePath path="c:/altera/10.0/ip/altera/sopc_builder_ip/altera_avalon_jtag_uart/inc"/>
<includePath path="c:/altera/10.0/ip/altera/nios2_ip/altera_nios2/HAL/inc"/>
<includePath path="c:/altera/10.0/nios2eds/components/altera_hal/HAL/inc"/>
<definedSymbol symbol="ALTERA_INCLUDES"/>
<definedSymbol symbol="SYSTEM_BUS_WIDTH=32"/>
<definedSymbol symbol="ALT_NO_INSTRUCTION_EMULATION"/>
<definedSymbol symbol="ALT_SINGLE_THREADED"/>
<definedSymbol symbol="__hal__"/>
<definedSymbol symbol="ALT_DEBUG"/>
</collector>
</scannerInfo>
