
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE2_115_WEB_SERVER(

	//////// CLOCK //////////
	OSC_50,
	NETCLK_25,

	//////// Sma //////////
	SMA_CLKIN,
	SMA_CLKOUT,

	//////// LED //////////
	LEDG,
	LEDR,

	//////// KEY //////////
	KEY,

	//////// SW //////////
	SW,

	//////// SEG7 //////////
	HEX0_D,
	HEX1_D,
	HEX2_D,
	HEX3_D,
	HEX4_D,
	HEX5_D,
	HEX6_D,
	HEX7_D,

	//////// LCD //////////
	LCD_BLON,
	LCD_DATA,
	LCD_EN,
	LCD_ON,
	LCD_RS,
	LCD_RW,

	//////// RS232 //////////
	UART_CTS,
	UART_RTS,
	UART_RXD,
	UART_TXD,

	//////// PS2 //////////
	PS2_KBCLK,
	PS2_KBDAT,
	PS2_MSCLK,
	PS2_MSDAT,

	//////// SDCARD //////////
	SD_CLK,
	SD_CMD,
	SD_DAT,
	SD_WP_n,

	//////// VGA //////////
	VGA_B,
	VGA_BLANK_n,
	VGA_CLK,
	VGA_G,
	VGA_HS,
	VGA_R,
	VGA_SYNC_n,
	VGA_VS,

	//////// Audio //////////
	AUD_ADCDAT,
	AUD_ADCLRCK,
	AUD_BCLK,
	AUD_DACDAT,
	AUD_DACLRCK,
	AUD_XCK,

	//////// I2C for EEPROM //////////
	EEP_I2C_SCL,
	EEP_I2C_SDA,

	//////// I2C for Audio and Tv-Decode //////////
	I2C_SCL,
	I2C_SDA,

	//////// Ethernet 0 //////////
	NET0_GTX_CLK,
	NET0_INT_n,
	NET0_MDC,
	NET0_MDIO,
	NET0_RESET_n,
	NET0_RX_CLK,
	NET0_RX_COL,
	NET0_RX_CRS,
	NET0_RX_DATA,
	NET0_RX_DV,
	NET0_RX_ER,
	NET0_TX_CLK,
	NET0_TX_DATA,
	NET0_TX_EN,
	NET0_TX_ER,
	NET0_LINK100,

	//////// Ethernet 1 //////////
	NET1_GTX_CLK,
	NET1_INT_n,
	NET1_MDC,
	NET1_MDIO,
	NET1_RESET_n,
	NET1_RX_CLK,
	NET1_RX_COL,
	NET1_RX_CRS,
	NET1_RX_DATA,
	NET1_RX_DV,
	NET1_RX_ER,
	NET1_TX_CLK,
	NET1_TX_DATA,
	NET1_TX_EN,
	NET1_TX_ER,
	NET1_LINK100,

	//////// TV Decoder //////////
	TD_CLK27,
	TD_DATA,
	TD_HS,
	TD_RESET_n,
	TD_VS,

    /////// USB OTG controller
    OTG_DATA,
    OTG_A,
    OTG_CS_n,
    OTG_WE_n,
    OTG_OE_n,
    OTG_INT,
    OTG_RESET_n,
    OTG_DREQ,
    OTG_DACK_n,
    OTG_FSPEED,
    OTG_LSPEED,
	//////// IR Receiver //////////
	IRDA_RXD,

	//////// SDRAM //////////
	DRAM_ADDR,
	DRAM_BA,
	DRAM_CAS_n,
	DRAM_CKE,
	DRAM_CLK,
	DRAM_CS_n,
	DRAM_DQ,
	DRAM_DQM,
	DRAM_RAS_n,
	DRAM_WE_n,

	//////// SRAM //////////
	SRAM_ADDR,
	SRAM_CE_n,
	SRAM_DQ,
	SRAM_LB_n,
	SRAM_OE_n,
	SRAM_UB_n,
	SRAM_WE_n,

	//////// Flash //////////
	FLASH_ADDR,
	FLASH_CE_n,
	FLASH_DQ,
	FLASH_OE_n,
	FLASH_RESET_n,
	FLASH_RY,
	FLASH_WE_n,
	FLASH_WP_n,

	//////// GPIO //////////
	GPIO_DATA,

	//////// HSMC (LVDS) //////////
//	HSMC_CLKIN_n1,
//	HSMC_CLKIN_n2,
	HSMC_CLKIN_p1,
	HSMC_CLKIN_p2,
	HSMC_CLKIN0,
//	HSMC_CLKOUT_n1,
//	HSMC_CLKOUT_n2,
	HSMC_CLKOUT_p1,
	HSMC_CLKOUT_p2,
	HSMC_CLKOUT0,
	HSMC_D,
//	HSMC_RX_D_n,
	HSMC_RX_D_p,
//	HSMC_TX_D_n,
	HSMC_TX_D_p,
    //////// EXTEND IO //////////
    EXT_IO	
);

//=======================================================
//  PARAMETER declarations
//=======================================================


//=======================================================
//  PORT declarations
//=======================================================

//////////// CLOCK //////////
input		     [2:0]		OSC_50;
input		          		NETCLK_25;

//////////// Sma //////////
input		          		SMA_CLKIN;
output		          		SMA_CLKOUT;

//////////// LED //////////
output		     [8:0]		LEDG;
output		    [17:0]		LEDR;

//////////// KEY //////////
input		     [3:0]		KEY;

//////////// SW //////////
input		    [17:0]		SW;

//////////// SEG7 //////////
output		     [6:0]		HEX0_D;
output		     [6:0]		HEX1_D;
output		     [6:0]		HEX2_D;
output		     [6:0]		HEX3_D;
output		     [6:0]		HEX4_D;
output		     [6:0]		HEX5_D;
output		     [6:0]		HEX6_D;
output		     [6:0]		HEX7_D;

//////////// LCD //////////
output		          		LCD_BLON;
inout		     [7:0]		LCD_DATA;
output		          		LCD_EN;
output		          		LCD_ON;
output		          		LCD_RS;
output		          		LCD_RW;

//////////// RS232 //////////
output		          		UART_CTS;
input		          		UART_RTS;
input		          		UART_RXD;
output		          		UART_TXD;

//////////// PS2 //////////
inout		          		PS2_KBCLK;
inout		          		PS2_KBDAT;
inout		          		PS2_MSCLK;
inout		          		PS2_MSDAT;

//////////// SDCARD //////////
output		          		SD_CLK;
inout		          		SD_CMD;
inout		     [3:0]		SD_DAT;
input		          		SD_WP_n;

//////////// VGA //////////
output		     [7:0]		VGA_B;
output		          		VGA_BLANK_n;
output		          		VGA_CLK;
output		     [7:0]		VGA_G;
output		          		VGA_HS;
output		     [7:0]		VGA_R;
output		          		VGA_SYNC_n;
output		          		VGA_VS;

//////////// Audio //////////
input		          		AUD_ADCDAT;
inout		          		AUD_ADCLRCK;
inout		          		AUD_BCLK;
output		          		AUD_DACDAT;
inout		          		AUD_DACLRCK;
output		          		AUD_XCK;

//////////// I2C for EEPROM //////////
output		          		EEP_I2C_SCL;
inout		          		EEP_I2C_SDA;

//////////// I2C for Audio and Tv-Decode //////////
output		          		I2C_SCL;
inout		          		I2C_SDA;

//////////// Ethernet 0 //////////
output		          		NET0_GTX_CLK;
input		          		NET0_INT_n;
output		          		NET0_MDC;
input		          		NET0_MDIO;
output		          		NET0_RESET_n;
input		          		NET0_RX_CLK;
input		          		NET0_RX_COL;
input		          		NET0_RX_CRS;
input		     [3:0]		NET0_RX_DATA;
input		          		NET0_RX_DV;
input		          		NET0_RX_ER;
input		          		NET0_TX_CLK;
output		     [3:0]		NET0_TX_DATA;
output		          		NET0_TX_EN;
output		          		NET0_TX_ER;
input		          		NET0_LINK100;

//////////// Ethernet 1 //////////
output		          		NET1_GTX_CLK;
input		          		NET1_INT_n;
output		          		NET1_MDC;
input		          		NET1_MDIO;
output		          		NET1_RESET_n;
input		          		NET1_RX_CLK;
input		          		NET1_RX_COL;
input		          		NET1_RX_CRS;
input		     [3:0]		NET1_RX_DATA;
input		          		NET1_RX_DV;
input		          		NET1_RX_ER;
input		          		NET1_TX_CLK;
output		     [3:0]		NET1_TX_DATA;
output		          		NET1_TX_EN;
output		          		NET1_TX_ER;
input		          		NET1_LINK100;

//////////// TV Decoder 1 //////////
input		          		TD_CLK27;
input		     [7:0]		TD_DATA;
input		          		TD_HS;
output		          		TD_RESET_n;
input		          		TD_VS;


//////////// USB OTG controller //////////
inout            [15:0]     OTG_DATA;
output           [1:0]      OTG_A;
output                      OTG_CS_n;
output                      OTG_WE_n;
output                      OTG_OE_n;
input            [1:0]      OTG_INT;
output                      OTG_RESET_n;
input            [1:0]      OTG_DREQ;
output           [1:0]      OTG_DACK_n;
inout                       OTG_FSPEED;
inout                       OTG_LSPEED;

//////////// IR Receiver //////////
input		          		IRDA_RXD;

//////////// SDRAM //////////
output		    [12:0]		DRAM_ADDR;
output		     [1:0]		DRAM_BA;
output		          		DRAM_CAS_n;
output		          		DRAM_CKE;
output		          		DRAM_CLK;
output		          		DRAM_CS_n;
inout		    [31:0]		DRAM_DQ;
output		     [3:0]		DRAM_DQM;
output		          		DRAM_RAS_n;
output		          		DRAM_WE_n;

//////////// SRAM //////////
output		    [19:0]		SRAM_ADDR;
output		          		SRAM_CE_n;
inout		    [15:0]		SRAM_DQ;
output		          		SRAM_LB_n;
output		          		SRAM_OE_n;
output		          		SRAM_UB_n;
output		          		SRAM_WE_n;

//////////// Flash //////////
output		    [22:0]		FLASH_ADDR;
output		          		FLASH_CE_n;
inout		     [7:0]		FLASH_DQ;
output		          		FLASH_OE_n;
output		          		FLASH_RESET_n;
input		          		FLASH_RY;
output		          		FLASH_WE_n;
output		          		FLASH_WP_n;

//////////// GPIO //////////
inout		    [35:0]		GPIO_DATA;

//////////// HSMC (LVDS) //////////

//input		          		HSMC_CLKIN_n1;
//input		          		HSMC_CLKIN_n2;
input		          		HSMC_CLKIN_p1;
input		          		HSMC_CLKIN_p2;
input		          		HSMC_CLKIN0;
//output		          		HSMC_CLKOUT_n1;
//output		          		HSMC_CLKOUT_n2;
output		          		HSMC_CLKOUT_p1;
output		          		HSMC_CLKOUT_p2;
output		          		HSMC_CLKOUT0;
inout		     [3:0]		HSMC_D;
//input		    [16:0]		HSMC_RX_D_n;
input		    [16:0]		HSMC_RX_D_p;
//output		    [16:0]		HSMC_TX_D_n;
output		    [16:0]		HSMC_TX_D_p;

//////// EXTEND IO //////////
inout		    [6:0]		EXT_IO;



//=======================================================
//  REG/WIRE declarations
//=======================================================



wire HEX0_DP;
wire HEX1_DP;
wire HEX2_DP;
wire HEX3_DP;
wire HEX4_DP;
wire HEX5_DP;
wire HEX6_DP;
wire HEX7_DP;


//=======================================================
//  Structural coding
//=======================================================
wire reset_n;

assign reset_n = 1'b1;

DE2_115_SOPC DE2_115_SOPC_inst(
                      // 1) global signals:
                       .clk_50(OSC_50[0]),
                       .reset_n(reset_n),
                       .altpll_25(VGA_CLK),
                       .altpll_io(),
                       .altpll_sdram(DRAM_CLK),
                       .altpll_sys(),                       

                      // the_audio
                       .avs_s1_export_ADCDAT_to_the_audio(AUD_ADCDAT),
                       .avs_s1_export_ADCLRC_to_the_audio(AUD_ADCLRCK),
                       .avs_s1_export_BCLK_to_the_audio(AUD_BCLK),
                       .avs_s1_export_DACDAT_from_the_audio(AUD_DACDAT),
                       .avs_s1_export_DACLRC_to_the_audio(AUD_DACLRCK),
                       .avs_s1_export_XCK_from_the_audio(AUD_XCK),

                      // the_eep_i2c_scl
                       .out_port_from_the_eep_i2c_scl(EEP_I2C_SCL),

                      // the_eep_i2c_sda
                       .bidir_port_to_and_from_the_eep_i2c_sda(EEP_I2C_SDA),

                      // the_i2c_scl
                       .out_port_from_the_i2c_scl(I2C_SCL),

                      // the_i2c_sda
                       .bidir_port_to_and_from_the_i2c_sda(I2C_SDA),

                      // the_ir
                       .in_port_to_the_ir(IRDA_RXD),

                      // the_key
                       .in_port_to_the_key(KEY),

                      // the_lcd
                       .LCD_E_from_the_lcd(LCD_EN),
                       .LCD_RS_from_the_lcd(LCD_RS),
                       .LCD_RW_from_the_lcd(LCD_RW),
                       .LCD_data_to_and_from_the_lcd(LCD_DATA),

                      // the_ledg
                       .out_port_from_the_ledg(LEDG),

                      // the_ledr
                       .out_port_from_the_ledr(LEDR),

                      // the_rs232
                       .cts_n_to_the_rs232(UART_CTS),
                       .rts_n_from_the_rs232(UART_RTS),
                       .rxd_to_the_rs232(UART_RXD),
                       .txd_from_the_rs232(UART_TXD),
                       
                      // the_sdram
                       .zs_addr_from_the_sdram(DRAM_ADDR),
                       .zs_ba_from_the_sdram(DRAM_BA),
                       .zs_cas_n_from_the_sdram(DRAM_CAS_n),
                       .zs_cke_from_the_sdram(DRAM_CKE),
                       .zs_cs_n_from_the_sdram(DRAM_CS_n),
                       .zs_dq_to_and_from_the_sdram(DRAM_DQ),
                       .zs_dqm_from_the_sdram(DRAM_DQM),
                       .zs_ras_n_from_the_sdram(DRAM_RAS_n),
                       .zs_we_n_from_the_sdram(DRAM_WE_n),
                       
                      // the_seg7
                       .SEG7_from_the_seg7({
                              HEX7_DP, HEX7_D, HEX6_DP, HEX6_D,
                              HEX5_DP, HEX5_D, HEX4_DP, HEX4_D, 
                              HEX3_DP, HEX3_D, HEX2_DP, HEX2_D,
                              HEX1_DP, HEX1_D, HEX0_DP, HEX0_D}),

                      // the_sma_in
                       .in_port_to_the_sma_in(SMA_CLKIN),

                      // the_sma_out
                       .out_port_from_the_sma_out(SMA_CLKOUT),

                      // the_sram
                       .SRAM_ADDR_from_the_sram(SRAM_ADDR),
                       .SRAM_CE_n_from_the_sram(SRAM_CE_n),
                       .SRAM_DQ_to_and_from_the_sram(SRAM_DQ),
                       .SRAM_LB_n_from_the_sram(SRAM_LB_n),
                       .SRAM_OE_n_from_the_sram(SRAM_OE_n),
                       .SRAM_UB_n_from_the_sram(SRAM_UB_n),
                       .SRAM_WE_n_from_the_sram(SRAM_WE_n),
                       
                      // the_sw
                       .in_port_to_the_sw(SW),

                      // the_tri_state_bridge_flash_avalon_slave
                       .address_to_the_cfi_flash(FLASH_ADDR),
                       .read_n_to_the_cfi_flash(FLASH_OE_n),
                       .select_n_to_the_cfi_flash(FLASH_CE_n),
                       .tri_state_bridge_flash_data(FLASH_DQ),
                       .write_n_to_the_cfi_flash(FLASH_WE_n),
                       
                      // sdcard
                       .out_port_from_the_sd_clk(SD_CLK),
                       .bidir_port_to_and_from_the_sd_cmd(SD_CMD),
                       .bidir_port_to_and_from_the_sd_dat(SD_DAT),
                       .in_port_to_the_sd_wp_n(SD_WP_n),
                       
                                                                    // the_usb
                       .USB_INT1_to_the_usb(OTG_INT[1]),
                       .USB_ADDR_from_the_usb(OTG_A),
                       .USB_CS_N_from_the_usb(OTG_CS_n),
                       .USB_DATA_to_and_from_the_usb(OTG_DATA),
                       .USB_INT0_to_the_usb(OTG_INT[0]),
                       .USB_RD_N_from_the_usb(OTG_OE_n),
                       .USB_RST_N_from_the_usb(OTG_RESET_n),
                       .USB_WR_N_from_the_usb(OTG_WE_n),
                       


                      // the_vpg
                       .vga_b_from_the_vpg(VGA_B),
                       .vga_clk_to_the_vpg(VGA_CLK),
                       .vga_de_from_the_vpg(),
                       .vga_g_from_the_vpg(VGA_G),
                       .vga_hs_from_the_vpg(VGA_HS),
                       .vga_r_from_the_vpg(VGA_R),
                       .vga_vs_from_the_vpg(VGA_VS)
                    );
                    
                 

// Flash Config
assign	FLASH_RESET_n = reset_n;
assign	FLASH_WP_n = 1'b1;
//	FLASH_RY,

///////////////////////////////////////////
// LCD config
assign LCD_BLON = 0; // not supported
assign LCD_ON = 1'b1; // alwasy on

wire io_dir;
wire action;
assign io_dir = KEY[0] & action;

///////////////////////////////////////////
// GPIO
assign GPIO_DATA[17:0] = (io_dir)?GPIO_DATA[35:18]:18'hz;
assign GPIO_DATA[35:18] = (io_dir)?GPIO_DATA[17:0]:18'hz;

///////////////////////////////////////////
// HSMC
assign HSMC_D[1:0] = (io_dir)?HSMC_D[3:2]:2'hz;
assign HSMC_D[3:2] = (io_dir)?HSMC_D[1:0]:2'hz;

assign HSMC_TX_D_p = HSMC_RX_D_p;
//assign HSMC_TX_D_n = HSMC_RX_D_n;

//assign HSMC_CLKOUT_n1 = HSMC_CLKIN_n1;
//assign HSMC_CLKOUT_n2 = HSMC_CLKIN_n2;
assign HSMC_CLKOUT_p1 = HSMC_CLKIN_p1;
assign HSMC_CLKOUT_p2 = HSMC_CLKIN_p2;
assign HSMC_CLKOUT0 = HSMC_CLKIN0;

///////////////////////////////////////////
// VGA
assign VGA_BLANK_n = 1'b1;
assign VGA_SYNC_n = 1'b1;


///////////////////////////////////////////
// NET
assign NET0_GTX_CLK = NET0_INT_n;
//assign NET0_GTX_CLK = NET0_MDIO;
assign NET0_MDC = NET0_RX_COL;
assign NET0_RESET_n = NET0_RX_CRS;
//assign NET0_RX_CLK = NET0_RX_DV;
assign NET0_TX_DATA = NET0_RX_DATA;
assign NET0_TX_EN = NET0_RX_ER;
assign NET0_TX_ER = NET0_TX_CLK;

assign NET1_GTX_CLK = NET1_INT_n;
//assign NET1_GTX_CLK = NET1_MDIO;
assign NET1_MDC = NET1_RX_COL;
assign NET1_RESET_n = NET1_RX_CRS;
//assign NET1_RX_CLK = NET1_RX_DV;
assign NET1_TX_DATA = NET1_RX_DATA;
assign NET1_TX_EN = NET1_RX_ER;
assign NET1_TX_ER = NET1_TX_CLK;

//assign ?? = {NET0_MDIO, NET0_RX_CLK, NET0_RX_DV};
//assign ?? = {NET1_MDIO, NET1_RX_CLK, NET1_RX_DV};

///////////////////////////////////////////
// USB OTG
//input            [1:0]      OTG_DREQ;
//output           [1:0]      OTG_DACK_n;
//inout                       OTG_FSPEED;
//inout                       OTG_LSPEED;                       
assign OTG_DACK_n = OTG_DREQ;
assign OTG_FSPEED = 1'b1;
assign OTG_LSPEED = 1'b0;

///////////////////////////////////////////
// TV
assign TD_RESET_n = TD_VS;
assign action = FLASH_RY & TD_HS & TD_CLK27 & (TD_DATA == 8'hff);

///////////////////////////////////////////
// ps2
assign PS2_KBCLK = PS2_KBDAT;
assign PS2_MSCLK = PS2_MSDAT;

endmodule
